services:
  theisland:
    image: ark-ascended-server-alex:latest
    ports:
      - "7777:7777/udp"
      - "27020:27020/tcp"
    environment:
      - SESSION_NAME=ValoriaArkASA-The Island
      - SERVER_PASSWORD=Valoria
      - SERVER_MAP=TheIsland_WP
      - SERVER_ADMIN_PASSWORD=Alex_25
      - GAME_PORT=7777
      - RCON_PORT=27020
      - CLUSTER_ID=arkclusterva
      - CLUSTER_DIR_OVERRIDE=/home/steam/ark/ShooterGame/Saved/Cluster
      - ENABLE_CROSS_TRAVEL=true
      - MOD_IDS=947033,929800,929868,1019389,942024,929489
      - MAX_PLAYERS=8
    volumes:
      - ./theisland:/home/steam/ark/ShooterGame/Saved
      - ./cluster:/home/steam/ark/ShooterGame/Saved/Cluster
      - ./extra.ini:/home/steam/ark/ShooterGame/Saved/Config/WindowsServer/extra.ini:ro


      dynamicconfig:
        image: python:3.11-slim
        container_name: dynamicconfig
        working_dir: /srv
        command: python -m http.server 8080 --bind 0.0.0.0
        ports:
          - "8080:8080"
        volumes:
          - ./dynamicconfig:/srv:ro
        restart: unless-stopped
  scorchedearth:
    image: ark-ascended-server-alex:latest
    ports:
      - "7778:7777/udp"
      - "27021:27020/tcp"
    environment:
      - SESSION_NAME=ValoriaArkASA-Scorched Earth
      - SERVER_PASSWORD=Valoria
      - SERVER_MAP=ScorchedEarth_WP
      - SERVER_ADMIN_PASSWORD=Alex_25
      - GAME_PORT=7777
      - RCON_PORT=27020
      - CLUSTER_ID=arkclusterva
      - CLUSTER_DIR_OVERRIDE=/home/steam/ark/ShooterGame/Saved/Cluster
      - ENABLE_CROSS_TRAVEL=true
      - MOD_IDS=947033,929800,929868,1019389,942024,929489
      - MAX_PLAYERS=8
    volumes:
      - ./scorchedearth:/home/steam/ark/ShooterGame/Saved
      - ./extra.ini:/home/steam/ark/ShooterGame/Saved/Config/WindowsServer/extra.ini:ro
      - ./cluster:/home/steam/ark/ShooterGame/Saved/Cluster

  ragnarok:
    image: ark-ascended-server-alex:latest
    ports:
      - "7779:7777/udp"
      - "27022:27020/tcp"
    environment:
      - SESSION_NAME=ValoriaArkASA-Ragnarok
      - SERVER_PASSWORD=Valoria
      - SERVER_MAP=Ragnarok_WP
      - SERVER_ADMIN_PASSWORD=Alex_25
      - GAME_PORT=7777
      - RCON_PORT=27020
      - CLUSTER_ID=arkclusterva
      - CLUSTER_DIR_OVERRIDE=/home/steam/ark/ShooterGame/Saved/Cluster
      - ENABLE_CROSS_TRAVEL=true
      - MOD_IDS=947033,929800,929868,1019389,942024,929489
      - MAX_PLAYERS=8
    volumes:
      - ./ragnarok:/home/steam/ark/ShooterGame/Saved
      - ./extra.ini:/home/steam/ark/ShooterGame/Saved/Config/WindowsServer/extra.ini:ro
      - ./cluster:/home/steam/ark/ShooterGame/Saved/Cluster

# No se requieren volumes de Docker, se usan bind mounts locales
