services:
  theisland:
    image: ark-ascended-server-alex:latest
    ports:
      - "7777:7777/udp"
      - "27020:27020/tcp"
    environment:
      - SESSION_NAME=Valoria Ark ASA - The Island
      - SERVER_PASSWORD=Valoria
      - SERVER_MAP=TheIsland_WP
      - SERVER_ADMIN_PASSWORD=Alex_25
      - GAME_PORT=7777
      - RCON_PORT=27020
      - CLUSTER_ID=arkcluster
      - ENABLE_CROSS_TRAVEL=true
      - MOD_IDS=947033,929800,929868,1019389,942024
      - MAX_PLAYERS=8
    volumes:
      - ./theisland:/home/steam/ark/ShooterGame/Saved
      - ./container/extra.ini:/home/steam/ark/ShooterGame/Saved/Config/WindowsServer/extra.ini:ro


  scorchedearth:
    image: ark-ascended-server-alex:latest
    ports:
      - "7778:7777/udp"
      - "27021:27020/tcp"
    environment:
      - SESSION_NAME=Valoria Ark ASA - Scorched Earth
      - SERVER_PASSWORD=Valoria
      - SERVER_MAP=ScorchedEarth_WP
      - SERVER_ADMIN_PASSWORD=Alex_25
      - GAME_PORT=7777
      - RCON_PORT=27020
      - CLUSTER_ID=arkcluster
      - ENABLE_CROSS_TRAVEL=true
      - MOD_IDS=947033,929800,929868,1019389,942024
      - MAX_PLAYERS=8
    volumes:
      - ./scorchedearth:/home/steam/ark/ShooterGame/Saved
      - ./container/extra.ini:/home/steam/ark/ShooterGame/Saved/Config/WindowsServer/extra.ini:ro

  ragnarok:
    image: ark-ascended-server-alex:latest
    ports:
      - "7779:7777/udp"
      - "27022:27020/tcp"
    environment:
      - SESSION_NAME=Valoria Ark ASA - Ragnarok
      - SERVER_PASSWORD=Valoria
      - SERVER_MAP=Ragnarok_WP
      - SERVER_ADMIN_PASSWORD=Alex_25
      - GAME_PORT=7777
      - RCON_PORT=27020
      - CLUSTER_ID=arkcluster
      - ENABLE_CROSS_TRAVEL=true
      - MOD_IDS=947033,929800,929868,1019389,942024
      - MAX_PLAYERS=8
    volumes:
      - ./ragnarok:/home/steam/ark/ShooterGame/Saved
      - ./container/extra.ini:/home/steam/ark/ShooterGame/Saved/Config/WindowsServer/extra.ini:ro

# No se requieren volumes de Docker, se usan bind mounts locales
